### ISSUE TITLE
What happens with NAs when partitioning

### ISSUE THREAD

**Issue by stephhazlitt** [thisisnic/introtoarrowrladiesottowa#21]
We should add a slide to demo what happens when you `write_dataset()` with a partition that has NAs -- we could use `mtcars` data. This was a nice question + IRL addition during the first IRL delivery of this content.

**Comment by stephhazlitt** [comment]
A nice reprex by @thisisnic demonstrating the default behaviour with NA in your partition variable when writing partitioned data, and how to take control of the behaviour (e.g., if you want name the NA folder/partition):

```
library(arrow)
library(tibble)

# Using the default settings
data <- tibble::tibble(
  x = 1:6,
  y = c(rep("group1", 5), NA)
)

data


tf <- tempfile()
dir.create(tf)

write_dataset(data, tf, partitioning = "y")
fs::dir_ls(tf)

# Now make it nicer
tf <- tempfile()
dir.create(tf)

write_dataset(data, tf,
              partitioning = hive_partition(y = string(),
                                            null_fallback = "no_group"))
fs::dir_ls(tf)
```

**Comment by thisisnic** [comment]
Thanks for adding this!  I think this is out of scope to incorporate into this workshop, but would make a great addition to the longer 1-day workshop.

**Comment by stephhazlitt** [comment]
Agreed. Added solution here in case it comes up and so we have it for revising the 1-day version.
